In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./data_source.csv')

In [6]:
df.head()

,Country,Code,Year,"GDP per capita, current U.S. dollars",Household consumption as percent of GDP,Unemployment rate,Personal income tax rate,"Taxes on goods and services, percent of total revenue",Real interest rate: Bank lending rate minus inflation,"Population size, in millions",Percent urban population,"Population density, people per square km",Annual HPI
0,China,CHN,2009,3832.24,35.33,4.72,45.0,60.11,5.53,1331.26,47.88,142,91.7975
1,China,CHN,2010,4550.45,34.33,4.53,45.0,63.37,-1.00,1337.70,49.23,142,100.0025
2,China,CHN,2011,5618.13,34.92,4.55,45.0,62.13,-1.40,1344.13,50.51,143,104.1175
3,China,CHN,2012,6316.92,35.39,4.57,45.0,61.33,3.58,1350.70,51.76,144,103.4225
4,China,CHN,2013,7050.65,35.83,4.59,45.0,57.98,3.76,1357.38,53.01,145,109.5550

In [11]:
print(df.columns)

Index(['Country', 'Code', 'Year', 'GDP per capita, current U.S. dollars',
       'Household consumption as percent of GDP', 'Unemployment rate',
       'Personal income tax rate',
       'Taxes on goods and services, percent of total revenue',
       'Real interest rate: Bank lending rate minus inflation',
       'Population size, in millions', 'Percent urban population',
       'Population density, people per square km', 'Annual HPI'],
      dtype='object')

In [24]:
for i in range(3, len(df.columns)):
#     display(df.groupby('Country').agg({df.columns[i]: ['mean', 'min', 'max', 'std']}))
    print(df.groupby('Country').agg({df.columns[i]: ['mean', 'min', 'max', 'std']}).to_latex(index=True))

\begin{tabular}{lrrrr}
\toprule
{} & \multicolumn{4}{l}{GDP per capita, current U.S. dollars} \\
{} &                                 mean &       min &       max &          std \\
Country     &                                      &           &           &              \\
\midrule
China       &                          7307.242727 &   3832.24 &  10261.68 &  2081.428551 \\
India       &                          1619.529091 &   1101.96 &   2104.15 &   308.639618 \\
Japan       &                         41070.663636 &  34524.47 &  48603.48 &  4334.089586 \\
Philippines &                          2821.324545 &   1905.89 &   3485.08 &   468.083442 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
{} & \multicolumn{4}{l}{Household consumption as percent of GDP} \\
{} &                                    mean &    min &    max &       std \\
Country     &                                         &        &        &           \\
\midrule
China       &                               36.779091 &  34.33 &  38.67 &  1.680770 \\
India       &                               57.820000 &  54.72 &  60.24 &  1.754685 \\
Japan       &                               57.220000 &  55.44 &  58.96 &  1.431642 \\
Philippines &                               72.208182 &  70.19 &  73.21 &  0.859032 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
{} & \multicolumn{4}{l}{Unemployment rate} \\
{} &              mean &   min &   max &       std \\
Country     &                   &       &       &           \\
\midrule
China       &          4.524545 &  4.28 &  4.72 &  0.131329 \\
India       &          5.542727 &  5.33 &  5.67 &  0.121416 \\
Japan       &          3.691818 &  2.29 &  5.10 &  0.999488 \\
Philippines &          3.134545 &  2.15 &  3.86 &  0.597518 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
{} & \multicolumn{4}{l}{Personal income tax rate} \\
{} &                     mean &   min &   max &       std \\
Country     &                          &       &       &           \\
\midrule
China       &                45.000000 &  45.0 &  45.0 &  0.000000 \\
India       &                33.363636 &  30.0 &  36.0 &  2.766685 \\
Japan       &                52.454545 &  50.0 &  56.0 &  2.841255 \\
Philippines &                32.545455 &  32.0 &  35.0 &  1.213560 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
{} & \multicolumn{4}{l}{Taxes on goods and services, percent of total revenue} \\
{} &                                                  mean &    min &    max &        std \\
Country     &                                                       &        &        &            \\
\midrule
China       &                                          46.751818 &  32.88 &  63.37 &  13.755032 \\
India       &                                          27.733636 &  21.68 &  31.76 &   3.586517 \\
Japan       &                                          36.270000 &  32.73 &  38.52 &   1.661614 \\
Philippines &                                          25.441818 &  22.67 &  27.28 &   1.401990 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
{} & \multicolumn{4}{l}{Real interest rate: Bank lending rate minus inflation} \\
{} &                                                  mean &   min &   max &       std \\
Country     &                                                       &       &       &           \\
\midrule
China       &                                           2.354545 & -1.40 &  5.53 &  2.353985 \\
India       &                                           4.380000 & -1.98 &  7.56 &  2.846601 \\
Japan       &                                           1.348182 & -0.98 &  3.56 &  1.429467 \\
Philippines &                                           3.963636 &  2.29 &  6.34 &  1.504980 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
{} & \multicolumn{4}{l}{Population size, in millions} \\
{} &                         mean &      min &      max &        std \\
Country     &                              &          &          &            \\
\midrule
China       &                  1364.741818 &  1331.26 &  1397.71 &  22.591435 \\
India       &                  1294.262727 &  1217.73 &  1366.42 &  49.124745 \\
Japan       &                   127.274545 &   126.26 &   128.07 &   0.601438 \\
Philippines &                   100.386364 &    92.41 &   108.12 &   5.253632 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
{} & \multicolumn{4}{l}{Percent urban population} \\
{} &                     mean &    min &    max &       std \\
Country     &                          &        &        &           \\
\midrule
China       &                54.210000 &  47.88 &  60.31 &  4.120017 \\
India       &                32.442727 &  30.59 &  34.47 &  1.286826 \\
Japan       &                91.204545 &  89.99 &  91.70 &  0.478359 \\
Philippines &                46.128182 &  45.33 &  47.15 &  0.625297 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
{} & \multicolumn{4}{l}{Population density, people per square km} \\
{} &                                     mean &  min &  max &        std \\
Country     &                                          &      &      &            \\
\midrule
China       &                               145.272727 &  142 &  148 &   2.327699 \\
India       &                               434.636364 &  410 &  455 &  15.279219 \\
Japan       &                               349.272727 &  347 &  351 &   1.420627 \\
Philippines &                               336.000000 &  310 &  358 &  16.540859 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
{} & \multicolumn{4}{l}{Annual HPI} \\
{} &        mean &      min &       max &        std \\
Country     &             &          &           &            \\
\midrule
China       &  112.306364 &  91.7975 &  137.5850 &  13.487503 \\
India       &  193.327273 &  84.1325 &  286.4600 &  71.959138 \\
Japan       &  104.448409 &  98.5825 &  113.9175 &   5.506789 \\
Philippines &  153.629773 &  99.4225 &  263.9175 &  52.967541 \\
\bottomrule
\end{tabular}