In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./data_source.csv')

In [6]:
df.head()

,Country,Code,Year,"GDP per capita, current U.S. dollars",Household consumption as percent of GDP,Unemployment rate,Personal income tax rate,"Taxes on goods and services, percent of total revenue",Real interest rate: Bank lending rate minus inflation,"Population size, in millions",Percent urban population,"Population density, people per square km",Annual HPI
0,China,CHN,2009,3832.24,35.33,4.72,45.0,60.11,5.53,1331.26,47.88,142,91.7975
1,China,CHN,2010,4550.45,34.33,4.53,45.0,63.37,-1.00,1337.70,49.23,142,100.0025
2,China,CHN,2011,5618.13,34.92,4.55,45.0,62.13,-1.40,1344.13,50.51,143,104.1175
3,China,CHN,2012,6316.92,35.39,4.57,45.0,61.33,3.58,1350.70,51.76,144,103.4225
4,China,CHN,2013,7050.65,35.83,4.59,45.0,57.98,3.76,1357.38,53.01,145,109.5550